--------------------------------------------------------
--  File created - Saturday-June-07-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FOLLOWING
--------------------------------------------------------

  CREATE TABLE "FOLLOWING" 
   (	"NAME" VARCHAR2(50 BYTE), 
	"IS_FOLLOWING" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FOLLOWING_COUNT
--------------------------------------------------------

  CREATE TABLE "FOLLOWING_COUNT" 
   (	"NAME" VARCHAR2(50 BYTE), 
	"AS_OF" DATE, 
	"COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROFILE
--------------------------------------------------------

  CREATE TABLE "PROFILE" 
   (	"SCREEN_NAME" VARCHAR2(50 BYTE), 
	"JOINED_ON" DATE, 
	"FAVORITES_CNT" NUMBER DEFAULT 0, 
	"FOLLOWERS_CNT" NUMBER DEFAULT 0, 
	"FRIENDS_CNT" NUMBER DEFAULT 0, 
	"LANGUAGE" VARCHAR2(20 BYTE), 
	"LOCATION" VARCHAR2(50 BYTE), 
	"TOTAL_STATUSES" NUMBER DEFAULT 0, 
	"LIST_CNT" NUMBER DEFAULT 0, 
	"USER_WEB_PAGE" VARCHAR2(150 BYTE), 
	"UPDATED_ON" DATE, 
	"GEO_POS" VARCHAR2(50 BYTE), 
	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAGS
--------------------------------------------------------

  CREATE TABLE "TAGS" 
   (	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAG_ACTIVITY
--------------------------------------------------------

  CREATE TABLE "TAG_ACTIVITY" 
   (	"NAME" VARCHAR2(50 BYTE), 
	"TAG_DATE" DATE, 
	"COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TWEETS
--------------------------------------------------------

  CREATE TABLE "TWEETS" 
   (	"ID" NUMBER, 
	"TEXT" VARCHAR2(140 BYTE), 
	"CREATED_ON" DATE, 
	"RETWEET_CNT" NUMBER DEFAULT 0, 
	"ORIGINAL_OWNER" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USED_TAG
--------------------------------------------------------

  CREATE TABLE "USED_TAG" 
   (	"NAME" VARCHAR2(50 BYTE), 
	"TAG" VARCHAR2(50 BYTE), 
	"COUNT" NUMBER DEFAULT 0, 
	"AS_OF" DATE, 
	"USED_ON" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FOLLOWING_COUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOLLOWING_COUNT_PK" ON "FOLLOWING_COUNT" ("NAME", "AS_OF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FOLLOWING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOLLOWING_PK" ON "FOLLOWING" ("NAME", "IS_FOLLOWING") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROFILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROFILE_PK" ON "PROFILE" ("SCREEN_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAGS_PK" ON "TAGS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAG_ACTIVITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAG_ACTIVITY_PK" ON "TAG_ACTIVITY" ("NAME", "TAG_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TWEETS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TWEETS_PK" ON "TWEETS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USED_TAG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USED_TAG_PK" ON "USED_TAG" ("NAME", "TAG", "USED_ON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FOLLOWING
--------------------------------------------------------

  ALTER TABLE "FOLLOWING" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "FOLLOWING" MODIFY ("IS_FOLLOWING" NOT NULL ENABLE);
  ALTER TABLE "FOLLOWING" ADD CONSTRAINT "FOLLOWING_PK" PRIMARY KEY ("NAME", "IS_FOLLOWING")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOLLOWING_COUNT
--------------------------------------------------------

  ALTER TABLE "FOLLOWING_COUNT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "FOLLOWING_COUNT" MODIFY ("AS_OF" NOT NULL ENABLE);
  ALTER TABLE "FOLLOWING_COUNT" MODIFY ("COUNT" NOT NULL ENABLE);
  ALTER TABLE "FOLLOWING_COUNT" ADD CONSTRAINT "FOLLOWING_COUNT_PK" PRIMARY KEY ("NAME", "AS_OF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFILE
--------------------------------------------------------

  ALTER TABLE "PROFILE" MODIFY ("SCREEN_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROFILE" MODIFY ("JOINED_ON" NOT NULL ENABLE);
  ALTER TABLE "PROFILE" ADD CONSTRAINT "PROFILE_PK" PRIMARY KEY ("SCREEN_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PROFILE" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "PROFILE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAGS
--------------------------------------------------------

  ALTER TABLE "TAGS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TAGS" ADD CONSTRAINT "TAGS_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAG_ACTIVITY
--------------------------------------------------------

  ALTER TABLE "TAG_ACTIVITY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TAG_ACTIVITY" MODIFY ("TAG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TAG_ACTIVITY" MODIFY ("COUNT" NOT NULL ENABLE);
  ALTER TABLE "TAG_ACTIVITY" ADD CONSTRAINT "TAG_ACTIVITY_PK" PRIMARY KEY ("NAME", "TAG_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TWEETS
--------------------------------------------------------

  ALTER TABLE "TWEETS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TWEETS" MODIFY ("TEXT" NOT NULL ENABLE);
  ALTER TABLE "TWEETS" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "TWEETS" ADD CONSTRAINT "TWEETS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USED_TAG
--------------------------------------------------------

  ALTER TABLE "USED_TAG" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "USED_TAG" MODIFY ("TAG" NOT NULL ENABLE);
  ALTER TABLE "USED_TAG" MODIFY ("COUNT" NOT NULL ENABLE);
  ALTER TABLE "USED_TAG" MODIFY ("AS_OF" NOT NULL ENABLE);
  ALTER TABLE "USED_TAG" ADD CONSTRAINT "USED_TAG_PK" PRIMARY KEY ("NAME", "TAG", "USED_ON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USED_TAG" MODIFY ("USED_ON" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FOLLOWING
--------------------------------------------------------

  ALTER TABLE "FOLLOWING" ADD CONSTRAINT "FOLLOWING_FK1" FOREIGN KEY ("NAME")
	  REFERENCES "PROFILE" ("SCREEN_NAME") ENABLE;
  ALTER TABLE "FOLLOWING" ADD CONSTRAINT "FOLLOWING_FK2" FOREIGN KEY ("IS_FOLLOWING")
	  REFERENCES "PROFILE" ("SCREEN_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOLLOWING_COUNT
--------------------------------------------------------

  ALTER TABLE "FOLLOWING_COUNT" ADD CONSTRAINT "FOLLOWING_COUNT_FK1" FOREIGN KEY ("NAME")
	  REFERENCES "PROFILE" ("SCREEN_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAG_ACTIVITY
--------------------------------------------------------

  ALTER TABLE "TAG_ACTIVITY" ADD CONSTRAINT "TAG_ACTIVITY_FK1" FOREIGN KEY ("NAME")
	  REFERENCES "TAGS" ("NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USED_TAG
--------------------------------------------------------

  ALTER TABLE "USED_TAG" ADD CONSTRAINT "USED_TAG_FK1" FOREIGN KEY ("NAME")
	  REFERENCES "PROFILE" ("SCREEN_NAME") ENABLE;
  ALTER TABLE "USED_TAG" ADD CONSTRAINT "USED_TAG_FK2" FOREIGN KEY ("TAG")
	  REFERENCES "TAGS" ("NAME") ENABLE;
